name: dcomic
description: A simple comic viewer application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.15+57

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: "^4.0.0"
  flutter_parallax: "^0.1.2"
  cached_network_image: "^3.1.0-alpha.1"
  flutter_cache_manager: ^3.1.0
  sqflite: ^2.0.0
  dio_cache_interceptor: ^2.3.1
  flutter_easyloading: ^3.0.0
  package_info: ^2.0.0
  url_launcher: ^6.0.3
  fluttericon: ^2.0.0
  flutter_webview_plugin: ^0.3.11
  markdown_widget:
    git: https://github.com/asjqkkkk/markdown_widget
  badges: ^1.1.6
  yin_drag_sacle: ^0.0.2
  flutter_swiper: ^1.1.6
  permission_handler: ^6.1.3
  path_provider: ^2.0.0
  provider: ^5.0.0
  toast: ^0.1.5
  uni_links: ^0.4.0
  share: ^2.0.1
  file_picker: ^3.0.1
  flutter_downloader: ^1.5.2
  logger: ^0.9.4
  flutter_widget_from_html: ^0.6.0
  flutter_easyrefresh: ^2.1.8
  connectivity: ^3.0.3
  battery: ^2.0.1
  flutter_spinkit: ^5.0.0
  version: ^2.0.0
  direct_select_flutter: ^1.0.7
  archive: ^3.1.2
  code_editor:
    git: https://github.com/hanerx/code_editor
  flutter_json_widget: ^1.0.2
  pretty_json: ^2.0.0
  lpinyin: ^2.0.1
  gbk2utf8: ^1.0.1
  flutter_archive: ^3.0.0
  sqlite3_flutter_libs: ^0.4.1
  firebase_core: "^1.0.3"
  firebase_analytics: "^8.0.0"
  firebase_crashlytics: "^2.0.0"
  firebase_auth: "^1.1.0"
  firebase_performance: "^0.7.0+3"
  crypton: ^2.0.1
  protobuf: ^2.0.0
  logger_flutter:
    git: https://github.com/ewertonrp/logger_flutter.git
  ipfs:
    git: https://github.com/hanerx/ipfs-dart.git
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/guide/chapter0/example0.json
    - assets/guide/chapter0/example1.json
    - assets/guide/chapter0/example2.json
    - assets/guide/chapter0/main.json
    - assets/guide/example.json
    - assets/js/lzString.js
    - assets/json/category.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
